### ISSUE TITLE
Fail to build docker-gpu for version 2.5

### ISSUE THREAD

**Issue by chuong98** [Xilinx/Vitis-AI#859]
Hello, after running the command `docker_build_gpu.sh`, my computer just hang, and does not show any progress after more than 5h waiting. Then I have to cancel. 
![image](https://user-images.githubusercontent.com/15174756/174049494-05ce06f9-b65b-4945-90b0-74d4ba4dee89.png)

**Comment by SuHuynh** [comment]
I also had the same problem when running command `docker_build_gpu.sh`. Anyone has solution?

**Comment by hanxue** [comment]
Hi,

There seems to be a problem with the conda channel link when building GPU docker. I am making some changes internally and verifying it, and will update the docker_build_gpu.sh script within the next 24 hours.

**Comment by hanxue** [comment]
Good news, the docker_build_gpu.sh script has been verified and updated. Please can you run `git pull` to refresh your local copy of Vitis AI repository and try running `sh docker_build_gpu.sh` script again?

**Comment by TC01** [comment]
Thanks for looking into this! I at least was able to build the container successfully.

**Comment by LorenzoSun-V** [comment]
> Hi,
> 
> There seems to be a problem with the conda channel link when building GPU docker. I am making some changes internally and verifying it, and will update the docker_build_gpu.sh script within the next 24 hours.

Thanks for your work ! It works well now!

**Comment by code-junki** [comment]
@hanxue are you sure the issue for the GPU docker is resolved? I did a pull few minutes ago and same result:

**Comment by JaviMota** [comment]
Hi 

I have cloned the repo again and the issue is still there. Same problem than @code-junki.

Thank you.

**Comment by janifer112x** [comment]
this issue has been fixed in the latest commit  on master branch
